---
- name: Apache for servers
  hosts: staging_servers_web:prod_servers
  become: yes

  vars:
    source_folder: /home/ec2-user/MySite
    destin_folder: /var/www/html

  tasks:
    
  - block:          #==============This block for RedHat============

      - name: Install Apache for Red Hat
        yum: name=httpd state=latest

      - name: Start apache eban
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"


  - block:            #=====================This block for Debian==================

      - name: Install Apache for Debian
        apt: name=apache2 state=latest

      - name: Start apache here
        service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

#  - name: Delete before load
#    file:
#       path: "{{ item }}"
#       state: absent   
#    with_fileglob:
#      - "/home/ec2-user/hui/*"
 
  - name: Move files to folder  
    copy: src={{ item }}  dest={{ destin_folder }} mode=0555
    with_fileglob:
        - "{{ source_folder }}/*.*" 
   

    notify:
      - Restart Apache for RedHat
      - Restart Apache for RedHat
 
  handlers:

  - name: Restart Apache for RedHat
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"    

  - name: Restart Apache for Debian
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"
